services:
  mysql:
    image: mysql:8.4.8
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 512m
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      interval: 2s
      timeout: 2s
      retries: 5

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 512m
#    environment:
#      JAVA_OPTS: "-Xms256m -Xmx256m"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana_data: