apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus        # 대시보드의 ${DS_PROMETHEUS}가 이 UID를 찾음
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: InfluxDB
    type: influxdb
    uid: influxdb          # 대시보드의 ${DS_INFLUXDB}가 이 UID를 찾음
    url: http://influxdb:8086
    access: proxy
    editable: true
    database: k6
